git:
  depth: 3
matrix:
  include:
  - name: "origin-contracts / js / dapp unit tests"
    language: node_js
    cache:
      npm: true
      directories:
        - origin-contracts/node_modules
        - origin-dapp/node_modules
        - origin-js/node_modules
    before_cache:
      - rm -rf origin-contracts/node_modules/.cache
      - rm -rf origin-dapp/node_modules/.cache
      - rm -rf origin-js/node_modules/.cache
    node_js: 10

  - name: "Origin-discovery unit tests"
    language: node_js
    cache:
      npm: true
      directories:
        - origin-contracts/node_modules
        - origin-dapp/node_modules
        - origin-js/node_modules
        - origin-discovery/node_modules
    before_cache:
      - rm -rf origin-contracts/node_modules/.cache
      - rm -rf origin-dapp/node_modules/.cache
      - rm -rf origin-js/node_modules/.cache
      - rm -rf origin-discovery/node_modules/.cache
    node_js: 10
    addons:
      postgresql: 9.6
    services:
      - postgresql
    env:
      - DATABASE_URL=postgres://postgres@localhost/travis_ci_test
    before_script:
      - psql -c 'create database travis_ci_test;' -U postgres
      - cd origin-discovery
      - npm run migrate

  - name: "Bridge server unit tests"
    language: python
    python: 3.6
    before_script:
      - cd origin-bridge
      - pip install -r requirements.txt
    script:
      - pytest --flakes --codestyle
