---
git:
  depth: 6
matrix:
  include:
    - name: "origin-graphql unit tests"
      language: node_js
      node_js: 10
      install:
        - npm install --ignore-scripts
        - npm run bootstrap -- --scope origin-contracts --scope origin-eventsource --scope origin-ipfs --scope origin-messaging-client --scope origin-services --scope origin-validator --scope origin-graphql
      script:
        - npm run test --prefix experimental/origin-graphql

    # Run integration tests using docker compose
    - name: "integration tests"
      language: minimal
      sudo: true
      before_script:
        # Setting required for Elasticsearch to run
        - sudo sysctl -w vm.max_map_count=262144
      script:
        - docker-compose -f docker-compose.yml -f docker-compose.test.yml up --exit-code-from origin-tests

    - name: "javascript linting"
      language: node_js
      node_js: 10
      cache:
        npm: true
        directories:
          - node_modules
      before_cache:
        - rm -rf node_modules/.cache
      install:
        - npm install --loglevel notice --dev-only --ignore-scripts
      script:
        - npm run lint

    - name: "origin-bridge unit tests"
      language: python
      python: 3.6
      before_script:
        - cd origin-bridge
        - pip install -r requirements.txt
      script:
        - pytest --flakes --codestyle

    - name: "origin-contracts unit tests"
      language: node_js
      node_js: 10
      install:
        - npm install --ignore-scripts
        - npm run bootstrap -- --scope origin-contracts
      script:
        - npm run test --prefix origin-contracts

    - name: "origin-discovery unit tests"
      language: node_js
      node_js: 10
      addons:
        postgresql: 9.6
      services:
        - postgresql
      env:
        - DATABASE_URL=postgres://postgres@localhost/travis_ci_test
      before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
        - lerna run migrate --scope origin-discovery
        - lerna run migrate --scope origin-growth
      install:
        - npm install --ignore-scripts
        - npm run bootstrap -- --scope origin-contracts --scope origin --scope origin-contracts --scope origin-eventsource --scope origin-ipfs --scope origin-messaging-client --scope origin-services --scope origin-validator --scope origin-graphql --scope origin-growth --scope origin-discovery
        - lerna run build --scope origin
        - node scripts/symlink-packages.js
      script:
        - npm run test --prefix origin-discovery

    - name: "origin-js unit tests"
      language: node_js
      node_js: 10
      install:
        - npm install --ignore-scripts
        - npm run bootstrap -- --scope origin-contracts --scope origin
      script:
        - npm run test --prefix origin-js

    - name: "origin-notifications unit tests"
      language: node_js
      node_js: 10
      install:
        - npm install --ignore-scripts
        - npm run bootstrap -- --scope origin-notifications
      script:
        - npm run test --prefix origin-notifications

    - name: "origin-token-transfer unit tests"
      language: node_js
      node_js: 10
      install:
        - npm install --ignore-scripts
        - npm run bootstrap -- --scope origin-contracts --scope origin-token --scope origin-token-transfer-client --scope origin-token-transfer-server
      script:
        - npm run test --prefix origin-token-transfer/server
        - npm run test --prefix origin-token-transfer/client
