databaseInstance: origin-214503:us-west1:dev

# origin-bridge
bridgeImage: origin-bridge
bridgeImageTag: 'd6fe5ca'

# origin-dapp
dappImage: origin-dapp
dappImageTag: '461880a'

# Origin network configuration
gethTxReplicas: 1
gethMinerReplicas: 2
gethMinerCpuLimit: 0.5

# ipfs
ipfsImage: ipfs/go-ipfs
ipfsImageTag: master

# ipfs-proxy
ipfsProxyImage: ipfs-proxy
ipfsProxyImageTag: '9d9ced5'

# origin-faucet
faucetImage: origin-faucet
faucetImageTag: '1732882'

# event-listener
eventlistenerImage: event-listener
eventlistenerImageTag: 'c58301a'

# origin-discovery
discoveryImage: origin-discovery
discoveryImageTag: 'c58301a'

# origin-messaging
messagingImage: origin-messaging
messagingImageTag: 'beba6fd'

# origin-notifications
notificationsImage: origin-notifications
notificationsImageTag: 'b4c0b52'
