containerRegistry: gcr.io/origin-214503

clusterIssuer: letsencrypt-prod

# origin-bridge
bridgeImage: origin-bridge
bridgeImageTag: latest
bridgeReplicas: 2

# origin-dapp
dappImage: origin-dapp
dappImageTag: latest
dappReplicas: 2

# origin-faucet
faucetImage: origin-faucet
faucetImageTag: latest

# ipfs
ipfsImage: ipfs/go-ipfs
ipfsImageTag: master

# origin-ipfs-proxy
ipfsProxyImage: ipfs-proxy
ipfsProxyImageTag: latest

# origin-messaging
messagingImage: origin-messaging
messagingImageTag: latest

# origin-notifications
notificationsImage: origin-notifications
notificationsImageTag: latest
