databaseInstance: origin-214503:us-west1:dev

# origin-bridge
bridgeImage: origin-bridge
bridgeImageTag: 'c86af29'

# origin-dapp
dappImage: origin-dapp
dappImageTag: 'caa56b0'

# ipfs
ipfsImage: ipfs/go-ipfs
ipfsImageTag: master

# origin-ipfs-proxy
ipfsProxyImage: origin-ipfs-proxy
ipfsProxyImageTag: '899b2e7'

# origin-faucet
faucetImage: origin-faucet
faucetImageTag: 'c86af29'

# event-listener
eventlistenerImage: event-listener
eventlistenerImageTag: '119f60b'

# origin-discovery
discoveryImage: origin-discovery
discoveryImageTag: '3e74bbf'

# origin-growth
growthImage: origin-growth
growthImageTag: 'c86af29'

# origin-messaging
messagingImage: origin-messaging
messagingImageTag: 'c86af29'

# origin-notifications
notificationsImage: origin-notifications
notificationsImageTag: 'c86af29'

# origin-dapp-creator-client
creatorClientImage: origin-dapp-creator-client
creatorClientImageTag: '6e34804'

# origin-dapp-creator-server
creatorServerImage: origin-dapp-creator-server
creatorServerImageTag: 'd94b81c'

# origin-dapp-creator-issuer
creatorIssuerImage: origin-dapp-creator-issuer
creatorIssuerImageTag: 'latest'
creatorIssuerIp: '35.233.181.44'

# origin-linking
linkingImage: origin-linking
linkingImageTag: '2328b60'

# origin-cron
cronImage: origin-cron
cronImageTag: '2328b60'
