databaseInstance: origin-214503:us-west1:dev

# origin-bridge
bridgeImage: origin-bridge
bridgeImageTag: '12ac36f'

# origin-dapp
dappImage: origin-dapp
dappImageTag: '391cc9c'

# origin-dapp2
dapp2Image: origin-dapp2
dapp2ImageTag: '340eb69'

# ipfs
ipfsImage: ipfs/go-ipfs
ipfsImageTag: master

# origin-ipfs-proxy
ipfsProxyImage: origin-ipfs-proxy
ipfsProxyImageTag: '899b2e7'

# origin-faucet
faucetImage: origin-faucet
faucetImageTag: '02fe2e6'

# event-listener
eventlistenerImage: event-listener
eventlistenerImageTag: '5b3b803'

# origin-discovery
discoveryImage: origin-discovery
discoveryImageTag: '5b3b803'

# origin-messaging
messagingImage: origin-messaging
messagingImageTag: '4a8c5fd'

# origin-notifications
notificationsImage: origin-notifications
notificationsImageTag: '30de4cf'

# origin-dapp-creator-client
creatorClientImage: origin-dapp-creator-client
creatorClientImageTag: '440d464'

# origin-dapp-creator-server
creatorServerImage: origin-dapp-creator-server
creatorServerImageTag: 'd94b81c'

# origin-dapp-creator-issuer
creatorIssuerImage: origin-dapp-creator-issuer
creatorIssuerImageTag: 'latest'
creatorIssuerIp: '35.233.181.44'

# origin-linking
linkingImage: origin-linking
linkingImageTag: '9dda30c'
