databaseInstance: origin-214503:us-west1:dev

# origin-bridge
bridgeImage: origin-bridge
bridgeImageTag: '12ac36f'

# origin-dapp
dappImage: origin-dapp
dappImageTag: '473079d'

# ipfs
ipfsImage: ipfs/go-ipfs
ipfsImageTag: master

# origin-ipfs-proxy
ipfsProxyImage: origin-ipfs-proxy
ipfsProxyImageTag: 'ab346df'

# origin-faucet
faucetImage: origin-faucet
faucetImageTag: '8efc326'

# event-listener
eventlistenerImage: event-listener
eventlistenerImageTag: 'a4f999b'

# origin-discovery
discoveryImage: origin-discovery
discoveryImageTag: '412cb1f'

# origin-messaging
messagingImage: origin-messaging
messagingImageTag: 'f5e9f62'

# origin-notifications
notificationsImage: origin-notifications
notificationsImageTag: '30de4cf'

# origin-dapp-creator-client
creatorClientImage: origin-dapp-creator-client
creatorClientImageTag: 'c235b98'

# origin-dapp-creator-server
creatorServerImage: origin-dapp-creator-server
creatorServerImageTag: '82c63a2'

# origin-dapp-creator-issuer
creatorIssuerImage: origin-dapp-creator-issuer
creatorIssuerImageTag: 'latest'
creatorIssuerIp: '35.233.181.44'

# origin-linking
linkingImage: origin-linking
linkingImageTag: '0db6ad2'
