name: origin-monitoring
description: Monitoring configuration to accompany Origin's primary chart
version: 0.1.0
home: https://github.com/OriginProtocol
icon: https://www.originprotocol.com/static/img/favicon/apple-touch-icon.png
sources:
  - https://github.com/OriginProtocol/origin/deployment/kubernetes/charts/origin-monitoring
