apiVersion: v1
kind: Service
metadata:
  name: {{ template "admin.fullname" . }}
  labels:
    app: {{ template "admin.fullname" . }}
    app.kubernetes.io/name: origin
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: origin-admin
spec:
  type: NodePort
  selector:
    app: {{ template "admin.fullname" . }}
  ports:
  - name: nginx
    port: 80
