apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "ethereum.fullname" . }}
  labels:
    app: {{ template "ethereum.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/ingress.class: {{ .Release.Namespace }}-ingress
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: {{ .Values.clusterIssuer }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/limit-rps: "2"
spec:
  tls:
    - secretName: {{ template "ethereum.host" . }}
      hosts:
        - {{ template "ethereum.host" . }}
  rules:
  - host: {{ template "ethereum.host" . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "ethereum.fullname" . }}-ethstats
          servicePort: 80
      - path: /rpc
        backend:
          serviceName: {{ template "ethereum.fullname" . }}
          servicePort: 8545
      # TODO use separate ingress and adjust for websocket
      - path: /ws
        backend:
          serviceName: {{ template "ethereum.fullname" . }}
          servicePort: 8546
