apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "faucet.fullname" . }}
  labels:
    app: {{ template "faucet.fullname" . }}
    app.kubernetes.io/name: origin
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: origin-faucet
spec:
  replicas: {{ default 2 .Values.faucetReplicas }}
  selector:
    matchLabels:
      app: {{ template "faucet.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "faucet.fullname" . }}
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: origin-faucet
        image: "{{ .Values.containerRegistry }}/{{ .Release.Namespace }}/{{ .Values.faucetImage }}:{{ .Values.faucetImageTag }}"
        imagePullPolicy: Always
        env:
        - name: ENVKEY
          valueFrom:
            secretKeyRef:
              name: {{ template "faucet.fullname" . }}
              key: ENVKEY
        ports:
        - containerPort: 5000
