apiVersion: v1
kind: Service
metadata:
  name: {{ template "ipfs.fullname" . }}
  labels:
    app: {{ template "ipfs.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  selector:
    app: {{ template "ipfs.fullname" . }}
  ports:
  - name: api
    port: 5001
  - name: gateway
    port: 8080
  - name: proxy
    port: 9999
