apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "ipfs.fullname" . }}
  labels:
    app: {{ template "ipfs.fullname" . }}
    app.kubernetes.io/name: origin
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: ipfs
  annotations:
    kubernetes.io/ingress.class: {{ .Release.Namespace }}-ingress
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: {{ .Values.clusterIssuer }}
    nginx.ingress.kubernetes.io/proxy-body-size: "2m"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/limit-rps: "50"
spec:
  tls:
    - secretName: {{ template "ipfs.host" . }}
      hosts:
        - {{ template "ipfs.host" . }}
    {{- if eq .Release.Namespace "prod" }}
    - secretName: gateway.originprotocol.com
      hosts:
        - gateway.originprotocol.com
    {{- end }}
  rules:
    - host: {{ template "ipfs.host" . }}
      http: &http_rules
        paths:
          - path: /
            backend:
              serviceName: {{ template "ipfs.fullname" . }}
              servicePort: 9999  # ipfs-proxy
          - path: /ipns
            backend:
              serviceName: {{ template "ipfs.fullname" . }}
              servicePort: 8080
    {{- if eq .Release.Namespace "prod" }}
    - host: gateway.originprotocol.com
      http: *http_rules
    {{- end }}
