databaseInstance: origin-214503:us-west1:dev

# origin-bridge
bridgeImage: origin-bridge
bridgeImageTag: 'b7aea6f'

# origin-dapp
dappImage: origin-dapp
dappImageTag: '8e919f6'

# origin-ipfs-proxy
ipfsProxyImage: origin-ipfs-proxy
ipfsProxyImageTag: '7428c36'

# origin-faucet
faucetImage: origin-faucet
faucetImageTag: 'f78d380'

# event-listener
eventlistenerImage: event-listener
eventlistenerImageTag: '2be6f7f'

# origin-discovery
discoveryImage: origin-discovery
discoveryImageTag: '7428c36'

# origin-growth
growthImage: origin-growth
growthImageTag: 'e8e8a9d'

# origin-messaging
messagingImage: origin-messaging
messagingImageTag: '72b91f2'

# origin-notifications
notificationsImage: origin-notifications
notificationsImageTag: '7428c36'

# origin-dapp-creator-client
creatorClientImage: origin-dapp-creator-client
creatorClientImageTag: '01ac496'

# origin-dapp-creator-server
creatorServerImage: origin-dapp-creator-server
creatorServerImageTag: '7428c36'

# origin-dapp-creator-issuer
creatorIssuerImage: origin-dapp-creator-issuer
creatorIssuerImageTag: 'latest'
creatorIssuerIp: '35.233.181.44'

# origin-cron
cronImage: origin-cron
cronImageTag: '7428c36'

# origin-admin
adminImage: origin-admin
adminImageTag: 'f78d380'

# origin-relayer
relayerImage: origin-relayer
relayerImageTag: 'b6212e7'

# origin-graphql
graphqlImage: origin-graphql
graphqlImageTag: '2be6f7f'
