databaseInstance: origin-214503:us-west1:prod

# origin-bridge
bridgeImage: origin-bridge
bridgeImageTag: '9539143'

# origin-dapp
dappImage: origin-dapp
dappImageTag: 'bb894e4'

# origin-ipfs-proxy
ipfsProxyImage: origin-ipfs-proxy
ipfsProxyImageTag: '9539143'

# origin-faucet
faucetImage: origin-faucet
faucetImageTag: '4a7a2d0'

# event-listener
eventlistenerImage: event-listener
eventlistenerImageTag: 'eff3325'

# origin-discovery
discoveryImage: origin-discovery
discoveryImageTag: '0e20ff3'

# origin-growth
growthImage: origin-growth
growthImageTag: '0e20ff3'

# origin-messaging
messagingImage: origin-messaging
messagingImageTag: 'a0d9e2f'

# origin-notifications
notificationsImage: origin-notifications
notificationsImageTag: '9539143'

# origin-dapp-creator-client
creatorClientImage: origin-dapp-creator-client
creatorClientImageTag: '98064bd'

# origin-dapp-creator-server
creatorServerImage: origin-dapp-creator-server
creatorServerImageTag: '9539143'

# origin-dapp-creator-issuer
creatorIssuerImage: origin-dapp-creator-issuer
creatorIssuerImageTag: 'latest'
creatorIssuerIp: '35.185.236.254'

# origin-linking
linkingImage: origin-linking
linkingImageTag: 'a0d9e2f'

# origin-cron
cronImage: origin-cron
cronImageTag: '25ade4b'

ipfsLoadBalancerIP: 35.233.189.126
