databaseInstance: origin-214503:us-west1:dev

# origin-bridge
bridgeImage: origin-bridge
bridgeImageTag: 'ed37ae1'

# origin-dapp
dappImage: origin-dapp
dappImageTag: '49ce34b'

# ipfs
ipfsImage: ipfs/go-ipfs
ipfsImageTag: master

# origin-ipfs-proxy
ipfsProxyImage: origin-ipfs-proxy
ipfsProxyImageTag: 'ed37ae1'

# origin-faucet
faucetImage: origin-faucet
faucetImageTag: '9b8aa9e'

# event-listener
eventlistenerImage: event-listener
eventlistenerImageTag: '0ebab0c'

# origin-discovery
discoveryImage: origin-discovery
discoveryImageTag: '3e74bbf'

# origin-growth
growthImage: origin-growth
growthImageTag: '6806657'

# origin-messaging
messagingImage: origin-messaging
messagingImageTag: '4681717'

# origin-notifications
notificationsImage: origin-notifications
notificationsImageTag: 'ed37ae1'

# origin-dapp-creator-client
creatorClientImage: origin-dapp-creator-client
creatorClientImageTag: '6e34804'

# origin-dapp-creator-server
creatorServerImage: origin-dapp-creator-server
creatorServerImageTag: 'd94b81c'

# origin-dapp-creator-issuer
creatorIssuerImage: origin-dapp-creator-issuer
creatorIssuerImageTag: 'latest'
creatorIssuerIp: '35.233.181.44'

# origin-linking
linkingImage: origin-linking
linkingImageTag: '2328b60'

# origin-cron
cronImage: origin-cron
cronImageTag: '6a6147d'

# origin-admin
adminImage: origin-admin
adminImageTag: '4999e14'
